// Generated by Selenium IDE
const {Builder, By, Key, until} = require('selenium-webdriver')
const assert = require('assert')
const chrome = require('selenium-webdriver/chrome');


describe('E2E Test', function () {
    this.timeout(30000)
    let driver
    let vars
    beforeEach(async function () {
        let options = new chrome.Options();
        options.addArguments('--headless'); // Run in headless mode
        driver = await new Builder().forBrowser('chrome').setChromeOptions(options).build();
        // Set a reasonable implicit wait time (e.g., 10 seconds)
        await driver.manage().setTimeouts({implicit: 10000});
        vars = {};
    });
    afterEach(async function () {
        if (driver) {
            await driver.quit();
        }
    });

    it('Should add a task', async function () {
    await driver.get("http://localhost:3000/");
    await driver.wait(until.titleIs('Your App Title'), 10000); // 等待页面标题加载
    await driver.manage().window().setRect({width: 1510, height: 871});
    await driver.findElement(By.css("input")).click();
    await driver.findElement(By.css("input")).sendKeys("this is a task");
    await driver.findElement(By.css("button:nth-child(2)")).click();
    await driver.findElement(By.css("button:nth-child(3)")).click();
    await driver.findElement(By.css("button:nth-child(4)")).click();
});
})

